"""empty message

Revision ID: 0acc6de04600
Revises: d24fb8dc04cd
Create Date: 2024-02-19 17:36:17.207557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0acc6de04600'
down_revision = 'd24fb8dc04cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('manufacturer',
               existing_type=postgresql.ENUM('Incom Corporation', 'Corellia Mining Corporation', name='manufacturer_types'),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('manufacturer',
               existing_type=sa.String(length=200),
               type_=postgresql.ENUM('Incom Corporation', 'Corellia Mining Corporation', name='manufacturer_types'),
               existing_nullable=False)

    # ### end Alembic commands ###
