"""empty message

Revision ID: 48de3331dfa8
Revises: 7ad4681f3cb8
Create Date: 2024-02-19 16:47:15.630559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48de3331dfa8'
down_revision = '7ad4681f3cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('hair_color',
               existing_type=postgresql.ENUM('brown', 'blond', 'red', 'black', 'n/a', name='hair_color_types'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=postgresql.ENUM('brown', 'green', 'blue', 'gold', 'n/a', name='eye_color_types'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('eye_color',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('brown', 'green', 'blue', 'gold', 'n/a', name='eye_color_types'),
               existing_nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('brown', 'blond', 'red', 'black', 'n/a', name='hair_color_types'),
               existing_nullable=False)

    # ### end Alembic commands ###
