"""empty message

Revision ID: d24fb8dc04cd
Revises: 48de3331dfa8
Create Date: 2024-02-19 17:13:19.168499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd24fb8dc04cd'
down_revision = '48de3331dfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('vehicle_class',
               existing_type=postgresql.ENUM('repulsorcraft', 'wheeled', 'starfighter', name='vehicle_class_types'),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('vehicle_class',
               existing_type=sa.String(length=150),
               type_=postgresql.ENUM('repulsorcraft', 'wheeled', 'starfighter', name='vehicle_class_types'),
               existing_nullable=False)

    # ### end Alembic commands ###
